### PR TITLE
[BugFix][ROCM]  The ROCM backend Bug Fix

### PR DESCRIPTION
**Pull request by zhangxiao-stack**
When using the ROCm backend to run MLC-LLM, the following bug was encountered and fixed. 
1、Module hip should be either dso exportable or binary ser
izable
2、 llvm.amdgcn.ds.bpermute Intrinsic has incorrect type
3、addrspace(3) @shmem Global is external, but doesn't …
…have external or weak linkage

### CODE REVIEW

**Comment by yzh119** [comment]
Hi @zhangxiao-stack , thanks so much for doing this, would you mind contributing the changes to TVM upstream? We expect the updates in Relax repo are all about Relax compiler/runtime, otherwise rebasing would be hard.

**Comment by tqchen** [comment]
Thank  you @zhangxiao-stack , please send it to apache tvm

**Comment by tqchen** [comment]
gentle ping @zhangxiao-stack

**Comment by tqchen** [comment]
This has been bought back to tvm. Thank you @zhangxiao-stack !

**Pull request closed without merging**
