### PR TITLE
[Relax] Add CopyRelaxFunction interface

### PR DESCRIPTION
**Pull request by Ubospica**
This PR adds a new interface `relax.utils.copy_relax_function` to copy functions:
```
def copy_relax_function(func: Function) -> Function:
    pass
```

The parameters of the original function would be copied to satisfy the restriction in the well-formed check: any two functions should not share the same parameter variable.

This interface serves for passes that needs to copy some existing function and modify it, such as `relax.transform.Gradient`.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
Thanks for the PR! One general remark is that this copy is not supposed to be a pass. Pass is referred as an “IRModule → IRModule” transformation, taking an input IRModule and transform it to a desired output one.

For this case of copy, it is for utility purpose. In a simple way you can put the interface in utils.h and the impl in utils.cc accordingly. You don’t need to wrap the interface to a Pass and don’t need to play with IRModule and GlobalVar. The interface takes a Function as input and returns the new one after copy.

https://github.com/mlc-ai/relax/blob/structinfo/include/tvm/relax/utils.h

**Comment by Ubospica** [comment]
> Thanks for the PR! One general remark is that this copy is not supposed to be a pass. Pass is referred as an “IRModule → IRModule” transformation, taking an input IRModule and transform it to a desired output one.
> 
> For this case of copy, it is for utility purpose. In a simple way you can put the interface in utils.h and the impl in utils.cc accordingly. You don’t need to wrap the interface to a Pass and don’t need to play with IRModule and GlobalVar. The interface takes a Function as input and returns the new one after copy.
> 
> [`structinfo`/include/tvm/relax/utils.h](https://github.com/mlc-ai/relax/blob/structinfo/include/tvm/relax/utils.h?rgh-link-date=2023-01-07T17%3A24%3A47Z)

Got it!
If we provide a Function to Function interface, the name of the copied function cannot be specified, because the name of Relax Function is stored in GlobalVar. Is that OK?
Besides, shall we provide a python interface as well, like `tvm.relax.utils.copy_relax_function`, to serve for use and tests in python side?

**Comment by MasterJH5574** [comment]
> > Thanks for the PR! One general remark is that this copy is not supposed to be a pass. Pass is referred as an “IRModule → IRModule” transformation, taking an input IRModule and transform it to a desired output one.
> > For this case of copy, it is for utility purpose. In a simple way you can put the interface in utils.h and the impl in utils.cc accordingly. You don’t need to wrap the interface to a Pass and don’t need to play with IRModule and GlobalVar. The interface takes a Function as input and returns the new one after copy.
> > [`structinfo`/include/tvm/relax/utils.h](https://github.com/mlc-ai/relax/blob/structinfo/include/tvm/relax/utils.h?rgh-link-date=2023-01-07T17%3A24%3A47Z)
> 
> Got it! If we provide a Function to Function interface, the name of the copied function cannot be specified, because the name of Relax Function is stored in GlobalVar. Is that OK? Besides, shall we provide a python interface as well, like `tvm.relax.utils.CopyRelaxFunction`, to serve for use and tests in python side?

@Ubospica For the first one, one Function does not necessarily have a name and does not necessarily relate with a GlobalVar (e.g., we can have local Function inside another Function). We should leave naming to the caller side.

For the second point, yes you’re right.

**Review by SiriusNEO — APPROVED** [review]
Looks good! But there are some problems with CI check. Maybe we need do a rebase or other things.

**Comment by MasterJH5574** [comment]
I’m thinking about the functionality and naming of this helper. For the first thing, we don’t need put “Relax” in the name. For the second thing, now it only copies a Function with fresh parameters. In this case, naming it “CopyFunction” is too general, because there might be Vars not implicated by the parameter substitution and thus not copied.

So it seems that we can either give it a more precise name, like “CopyWithNewParam”, or reconstruct every binding variable in the function. We don’t yet have a concrete need for copying the entire function, so going with the first choice is fine at this moment, as it is always easy to change the impl from “only param copied” to “all variable copied”.

**Comment by Ubospica** [comment]
Replaced by #91

**Pull request closed without merging**
