### PR TITLE
[MLC][CI] Try to setup win mac building CI

### PR DESCRIPTION
**Pull request by Hzfengsy**
This PR adds CI for Windows and macOS building, which may take 90-100 mins

cc @tqchen @MasterJH5574

### CODE REVIEW

**Review by MasterJH5574 — APPROVED** [review]
Thanks!

**Comment by MasterJH5574** [comment]
Just want to get a sense: do you have idea on how frequently the win/mac build CI breaks?

**Comment by tqchen** [comment]
Sorry I merged pre-maturely. I reverted in #105 A better approach that will create less merge conflict would be to create a separate yaml, say mlc_relax.yml and add the workflow there

**Comment by MasterJH5574** [comment]
I brought a separate file in #106. Let’s see how it works.

**Pull request merged**
