### PR TITLE
[Relax] Bitwise and logical binary ops (AND, OR, XOR)

### PR DESCRIPTION
**Pull request by vvchernov**
Bitwise and logical binary ops were added to Relax. Part of them is needed to support MPT-like model on Relax

cc @tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @vvchernov can we send these to unity branch? We will then pull these changes in

**Comment by vvchernov** [comment]
Hello @tqchen! Yes I can do it on unity branch of apache/tvm. But I understand that NOT op is also needed for me, I think I add it here.

**Comment by vvchernov** [comment]
Hello @tqchen! Done: https://github.com/apache/tvm/pull/15075

**Comment by vvchernov** [comment]
Merged into original apache/tvm/unity and upstreamed

**Pull request closed without merging**
